# Generated by Django 2.2.6 on 2019-10-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(blank=True, default=1)),
                ('aux_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nsemester', models.IntegerField(choices=[(5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno'), (10, 'Decimo')])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('period', models.IntegerField(choices=[(1, 'Otoño'), (2, 'Primavera')])),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('state', models.CharField(choices=[(1, 'Terminado'), (2, 'En ejecucion'), (3, 'Por comenzar')], default=3, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSpreadSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('evaluation_type', models.IntegerField(choices=[(1, 'Control'), (2, 'Tarea')])),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uplanning.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uplanning.Ramo'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uplanning.Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uplanning.Teacher'),
        ),
    ]
