# Generated by Django 2.2.6 on 2019-10-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('evaluation_type', models.CharField(choices=[(1, 'Control'), (2, 'Tarea')], max_length=100)),
            ],
        ),
    ]
