# Generated by Django 2.2.6 on 2019-10-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, 'Otoño'), (2, 'Primavera')])),
                ('year', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('state', models.CharField(choices=[('finished', 'Terminado'), ('current', 'En ejecucion'), ('preparing', 'Por comenzar')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.IntegerField(choices=[(1, 'Control'), (2, 'Tarea')]),
        ),
    ]
