# Generated by Django 2.2.6 on 2019-10-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplanning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='aux_description',
            new_name='description',
        ),
    ]
