# Generated by Django 2.2.6 on 2019-10-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplanning', '0002_auto_20191014_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(),
        ),
    ]
