openapi: "3.0.2"
info: 
  title: umonitor
  description: Este es el archivo de OpenAPI que define las interacciones posibles con nuestro backend
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "0.1.0"

paths:
  /cursos:
    get:
      tags:
        - cursos
      summary: Lee todos los cursos
      description: Devuelve la lista completa de cursos
      operationId: cursos.read_all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/curso'
                  
    post:
      tags:
        - cursos
      summary: Crea un nuevo cursos
      description: Crea un nuevo curso
      operationId: cursos.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/curso'
      responses:
        '201':
          description: El curso fue creado
        '409':
          description: El curso ya existe

  /cursos/{nombre}/{seccion}:
    parameters:
        - in: path
          name: nombre
          description: El nombre del curso
          required: true
          schema:
            type: string
        - in: path
          name: seccion
          description: La seccion del curso
          required: true
          schema:
            type: integer
    get:
      tags:
        - cursos
      summary: Lee un curso
      description: Lee un solo curso de la base de datos
      operationId: cursos.read_one
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/curso'
        '404':
          description: El curso no esta
    put:
      tags:
        - cursos
      summary: Actualiza un curso
      description: Actualiza la informacion de un curso
      operationId: cursos.update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/curso'
      responses:
        '200':
          description: El curso fue actualizado
        '404':
          description: El curso no existe

        

components:
  schemas:
    curso:
      type: object
      properties:
        # un curso deberia tener anno y semestre, pero para simplificar por
        # ahora no va a tener ninguno de los dos, siempre seran de 2019-2
        # anno:
        #   type: integer
        # semestre:
        #   type: integer
        nombre:
          type: string
        seccion:
          type: integer
        profesor:
          type: string
        evaluaciones:
          type: object
          properties:
            controles:
              type: array
              items:
                type: string
            tareas:
              type: array
              items:
                type: string
      required:
        # - anno
        # - semestre
        - nombre
        - seccion

